name: InfiniteInventory
version: 1.0.0
main: me.kevinnovak.infiniteinventory.InfiniteInventory
author: KevinNovak
description: Carry as many items as you'd like.

commands:
    testsave:
        usage: /<command>
        description: Test.
        aliases: [iisave]
    testnext:
        usage: /<command>
        description: Test.
        aliases: [iinext]
    testprev:
        usage: /<command>
        description: Test.
        aliases: [iiprev]
