# Configuration file for InfiniteInventory
# Created by KevinNovak

# Whether or not to collect data on plugin usage
# Viewable at http://mcstats.org/plugin/InfiniteInventory/
# default: metrics: true
metrics: true
