# Configuration file for InventoryPages
# Created by KevinNovak

# Whether or not to collect data on plugin usage
# Viewable at http://mcstats.org/plugin/InventoryPages/
# default: metrics: true
metrics: true

items:
    prev:
        ID: 388
        name: '&6Prev Page'
        lore:
        - '&3This is a test'
        - '&3This is a test'
    next:
        ID: 264
        name: '&6Next Page'
        lore:
        - '&3This is a test'
        - '&3This is a test'
    noAction:
        ID: 1
        name: '&6No Pages'
        lore:
        - '&3This is a test'
        - '&3This is a test'    